/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallRoomIdRouteImport } from './routes/call/$roomId'
import { Route as ApiSectorsRouteImport } from './routes/api/sectors'
import { Route as ApiQuickResponsesRouteImport } from './routes/api/quick-responses'
import { Route as ApiOperatorsRouteImport } from './routes/api/operators'
import { Route as ApiGroupsRouteImport } from './routes/api/groups'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiChatsRouteImport } from './routes/api/chats'
import { Route as ApiCallsRouteImport } from './routes/api/calls'
import { Route as ApiContactsContactIdRouteImport } from './routes/api/contacts/$contactId'
import { Route as ApiChatsUpdateQueueRouteImport } from './routes/api/chats/update-queue'
import { Route as ApiBaileysSyncAvatarsRouteImport } from './routes/api/baileys/sync-avatars'
import { Route as ApiBaileysStatusRouteImport } from './routes/api/baileys/status'
import { Route as ApiBaileysSendMediaRouteImport } from './routes/api/baileys/send-media'
import { Route as ApiBaileysSendRouteImport } from './routes/api/baileys/send'
import { Route as ApiBaileysMediaRouteImport } from './routes/api/baileys/media'
import { Route as ApiBaileysDisconnectRouteImport } from './routes/api/baileys/disconnect'
import { Route as ApiBaileysConnectRouteImport } from './routes/api/baileys/connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoomIdRoute = CallRoomIdRouteImport.update({
  id: '/call/$roomId',
  path: '/call/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSectorsRoute = ApiSectorsRouteImport.update({
  id: '/api/sectors',
  path: '/api/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickResponsesRoute = ApiQuickResponsesRouteImport.update({
  id: '/api/quick-responses',
  path: '/api/quick-responses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorsRoute = ApiOperatorsRouteImport.update({
  id: '/api/operators',
  path: '/api/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsRoute = ApiGroupsRouteImport.update({
  id: '/api/groups',
  path: '/api/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsRoute = ApiChatsRouteImport.update({
  id: '/api/chats',
  path: '/api/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsRoute = ApiCallsRouteImport.update({
  id: '/api/calls',
  path: '/api/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsContactIdRoute = ApiContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiChatsUpdateQueueRoute = ApiChatsUpdateQueueRouteImport.update({
  id: '/update-queue',
  path: '/update-queue',
  getParentRoute: () => ApiChatsRoute,
} as any)
const ApiBaileysSyncAvatarsRoute = ApiBaileysSyncAvatarsRouteImport.update({
  id: '/api/baileys/sync-avatars',
  path: '/api/baileys/sync-avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysStatusRoute = ApiBaileysStatusRouteImport.update({
  id: '/api/baileys/status',
  path: '/api/baileys/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysSendMediaRoute = ApiBaileysSendMediaRouteImport.update({
  id: '/api/baileys/send-media',
  path: '/api/baileys/send-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysSendRoute = ApiBaileysSendRouteImport.update({
  id: '/api/baileys/send',
  path: '/api/baileys/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysMediaRoute = ApiBaileysMediaRouteImport.update({
  id: '/api/baileys/media',
  path: '/api/baileys/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysDisconnectRoute = ApiBaileysDisconnectRouteImport.update({
  id: '/api/baileys/disconnect',
  path: '/api/baileys/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysConnectRoute = ApiBaileysConnectRouteImport.update({
  id: '/api/baileys/connect',
  path: '/api/baileys/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/groups': typeof ApiGroupsRoute
  '/api/operators': typeof ApiOperatorsRoute
  '/api/quick-responses': typeof ApiQuickResponsesRoute
  '/api/sectors': typeof ApiSectorsRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/send-media': typeof ApiBaileysSendMediaRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/baileys/sync-avatars': typeof ApiBaileysSyncAvatarsRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/groups': typeof ApiGroupsRoute
  '/api/operators': typeof ApiOperatorsRoute
  '/api/quick-responses': typeof ApiQuickResponsesRoute
  '/api/sectors': typeof ApiSectorsRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/send-media': typeof ApiBaileysSendMediaRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/baileys/sync-avatars': typeof ApiBaileysSyncAvatarsRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/groups': typeof ApiGroupsRoute
  '/api/operators': typeof ApiOperatorsRoute
  '/api/quick-responses': typeof ApiQuickResponsesRoute
  '/api/sectors': typeof ApiSectorsRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/send-media': typeof ApiBaileysSendMediaRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/baileys/sync-avatars': typeof ApiBaileysSyncAvatarsRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/calls'
    | '/api/chats'
    | '/api/contacts'
    | '/api/groups'
    | '/api/operators'
    | '/api/quick-responses'
    | '/api/sectors'
    | '/call/$roomId'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/send'
    | '/api/baileys/send-media'
    | '/api/baileys/status'
    | '/api/baileys/sync-avatars'
    | '/api/chats/update-queue'
    | '/api/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/calls'
    | '/api/chats'
    | '/api/contacts'
    | '/api/groups'
    | '/api/operators'
    | '/api/quick-responses'
    | '/api/sectors'
    | '/call/$roomId'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/send'
    | '/api/baileys/send-media'
    | '/api/baileys/status'
    | '/api/baileys/sync-avatars'
    | '/api/chats/update-queue'
    | '/api/contacts/$contactId'
  id:
    | '__root__'
    | '/'
    | '/api/calls'
    | '/api/chats'
    | '/api/contacts'
    | '/api/groups'
    | '/api/operators'
    | '/api/quick-responses'
    | '/api/sectors'
    | '/call/$roomId'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/send'
    | '/api/baileys/send-media'
    | '/api/baileys/status'
    | '/api/baileys/sync-avatars'
    | '/api/chats/update-queue'
    | '/api/contacts/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCallsRoute: typeof ApiCallsRoute
  ApiChatsRoute: typeof ApiChatsRouteWithChildren
  ApiContactsRoute: typeof ApiContactsRouteWithChildren
  ApiGroupsRoute: typeof ApiGroupsRoute
  ApiOperatorsRoute: typeof ApiOperatorsRoute
  ApiQuickResponsesRoute: typeof ApiQuickResponsesRoute
  ApiSectorsRoute: typeof ApiSectorsRoute
  CallRoomIdRoute: typeof CallRoomIdRoute
  ApiBaileysConnectRoute: typeof ApiBaileysConnectRoute
  ApiBaileysDisconnectRoute: typeof ApiBaileysDisconnectRoute
  ApiBaileysMediaRoute: typeof ApiBaileysMediaRoute
  ApiBaileysSendRoute: typeof ApiBaileysSendRoute
  ApiBaileysSendMediaRoute: typeof ApiBaileysSendMediaRoute
  ApiBaileysStatusRoute: typeof ApiBaileysStatusRoute
  ApiBaileysSyncAvatarsRoute: typeof ApiBaileysSyncAvatarsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$roomId': {
      id: '/call/$roomId'
      path: '/call/$roomId'
      fullPath: '/call/$roomId'
      preLoaderRoute: typeof CallRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sectors': {
      id: '/api/sectors'
      path: '/api/sectors'
      fullPath: '/api/sectors'
      preLoaderRoute: typeof ApiSectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-responses': {
      id: '/api/quick-responses'
      path: '/api/quick-responses'
      fullPath: '/api/quick-responses'
      preLoaderRoute: typeof ApiQuickResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operators': {
      id: '/api/operators'
      path: '/api/operators'
      fullPath: '/api/operators'
      preLoaderRoute: typeof ApiOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups': {
      id: '/api/groups'
      path: '/api/groups'
      fullPath: '/api/groups'
      preLoaderRoute: typeof ApiGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats': {
      id: '/api/chats'
      path: '/api/chats'
      fullPath: '/api/chats'
      preLoaderRoute: typeof ApiChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls': {
      id: '/api/calls'
      path: '/api/calls'
      fullPath: '/api/calls'
      preLoaderRoute: typeof ApiCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts/$contactId': {
      id: '/api/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/api/contacts/$contactId'
      preLoaderRoute: typeof ApiContactsContactIdRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/chats/update-queue': {
      id: '/api/chats/update-queue'
      path: '/update-queue'
      fullPath: '/api/chats/update-queue'
      preLoaderRoute: typeof ApiChatsUpdateQueueRouteImport
      parentRoute: typeof ApiChatsRoute
    }
    '/api/baileys/sync-avatars': {
      id: '/api/baileys/sync-avatars'
      path: '/api/baileys/sync-avatars'
      fullPath: '/api/baileys/sync-avatars'
      preLoaderRoute: typeof ApiBaileysSyncAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/status': {
      id: '/api/baileys/status'
      path: '/api/baileys/status'
      fullPath: '/api/baileys/status'
      preLoaderRoute: typeof ApiBaileysStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/send-media': {
      id: '/api/baileys/send-media'
      path: '/api/baileys/send-media'
      fullPath: '/api/baileys/send-media'
      preLoaderRoute: typeof ApiBaileysSendMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/send': {
      id: '/api/baileys/send'
      path: '/api/baileys/send'
      fullPath: '/api/baileys/send'
      preLoaderRoute: typeof ApiBaileysSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/media': {
      id: '/api/baileys/media'
      path: '/api/baileys/media'
      fullPath: '/api/baileys/media'
      preLoaderRoute: typeof ApiBaileysMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/disconnect': {
      id: '/api/baileys/disconnect'
      path: '/api/baileys/disconnect'
      fullPath: '/api/baileys/disconnect'
      preLoaderRoute: typeof ApiBaileysDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/connect': {
      id: '/api/baileys/connect'
      path: '/api/baileys/connect'
      fullPath: '/api/baileys/connect'
      preLoaderRoute: typeof ApiBaileysConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiChatsRouteChildren {
  ApiChatsUpdateQueueRoute: typeof ApiChatsUpdateQueueRoute
}

const ApiChatsRouteChildren: ApiChatsRouteChildren = {
  ApiChatsUpdateQueueRoute: ApiChatsUpdateQueueRoute,
}

const ApiChatsRouteWithChildren = ApiChatsRoute._addFileChildren(
  ApiChatsRouteChildren,
)

interface ApiContactsRouteChildren {
  ApiContactsContactIdRoute: typeof ApiContactsContactIdRoute
}

const ApiContactsRouteChildren: ApiContactsRouteChildren = {
  ApiContactsContactIdRoute: ApiContactsContactIdRoute,
}

const ApiContactsRouteWithChildren = ApiContactsRoute._addFileChildren(
  ApiContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCallsRoute: ApiCallsRoute,
  ApiChatsRoute: ApiChatsRouteWithChildren,
  ApiContactsRoute: ApiContactsRouteWithChildren,
  ApiGroupsRoute: ApiGroupsRoute,
  ApiOperatorsRoute: ApiOperatorsRoute,
  ApiQuickResponsesRoute: ApiQuickResponsesRoute,
  ApiSectorsRoute: ApiSectorsRoute,
  CallRoomIdRoute: CallRoomIdRoute,
  ApiBaileysConnectRoute: ApiBaileysConnectRoute,
  ApiBaileysDisconnectRoute: ApiBaileysDisconnectRoute,
  ApiBaileysMediaRoute: ApiBaileysMediaRoute,
  ApiBaileysSendRoute: ApiBaileysSendRoute,
  ApiBaileysSendMediaRoute: ApiBaileysSendMediaRoute,
  ApiBaileysStatusRoute: ApiBaileysStatusRoute,
  ApiBaileysSyncAvatarsRoute: ApiBaileysSyncAvatarsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
