/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallRoomIdRouteImport } from './routes/call/$roomId'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiSectorsRouteImport } from './routes/api/sectors'
import { Route as ApiQuickResponsesRouteImport } from './routes/api/quick-responses'
import { Route as ApiOperatorsRouteImport } from './routes/api/operators'
import { Route as ApiGroupsRouteImport } from './routes/api/groups'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiChatsRouteImport } from './routes/api/chats'
import { Route as ApiCallsRouteImport } from './routes/api/calls'
import { Route as ApiValentinaSupervisorRouteImport } from './routes/api/valentina/supervisor'
import { Route as ApiValentinaSdrRouteImport } from './routes/api/valentina/sdr'
import { Route as ApiValentinaRodizioRouteImport } from './routes/api/valentina/rodizio'
import { Route as ApiValentinaMessagesRouteImport } from './routes/api/valentina/messages'
import { Route as ApiValentinaKnowledgeRouteImport } from './routes/api/valentina/knowledge'
import { Route as ApiValentinaConfigRouteImport } from './routes/api/valentina/config'
import { Route as ApiValentinaAgentsRouteImport } from './routes/api/valentina/agents'
import { Route as ApiSettingsReportsRouteImport } from './routes/api/settings/reports'
import { Route as ApiSettingsRdCrmRouteImport } from './routes/api/settings/rd-crm'
import { Route as ApiGestaoTasksRouteImport } from './routes/api/gestao/tasks'
import { Route as ApiGestaoSlaRouteImport } from './routes/api/gestao/sla'
import { Route as ApiGestaoReportsRouteImport } from './routes/api/gestao/reports'
import { Route as ApiGestaoPerformanceRouteImport } from './routes/api/gestao/performance'
import { Route as ApiGestaoOverviewRouteImport } from './routes/api/gestao/overview'
import { Route as ApiGestaoOperatorHistoryRouteImport } from './routes/api/gestao/operator-history'
import { Route as ApiGestaoMyMetricsRouteImport } from './routes/api/gestao/my-metrics'
import { Route as ApiGestaoMessagesRouteImport } from './routes/api/gestao/messages'
import { Route as ApiGestaoLiveRouteImport } from './routes/api/gestao/live'
import { Route as ApiGestaoHealthRouteImport } from './routes/api/gestao/health'
import { Route as ApiGestaoCostsRouteImport } from './routes/api/gestao/costs'
import { Route as ApiGestaoContactsAnalyticsRouteImport } from './routes/api/gestao/contacts-analytics'
import { Route as ApiGestaoAuditsRouteImport } from './routes/api/gestao/audits'
import { Route as ApiGestaoAlertsRouteImport } from './routes/api/gestao/alerts'
import { Route as ApiContactsUpdateWalletRouteImport } from './routes/api/contacts/update-wallet'
import { Route as ApiContactsContactIdRouteImport } from './routes/api/contacts/$contactId'
import { Route as ApiChatsUpdateQueueRouteImport } from './routes/api/chats/update-queue'
import { Route as ApiBaileysSyncAvatarsRouteImport } from './routes/api/baileys/sync-avatars'
import { Route as ApiBaileysStatusRouteImport } from './routes/api/baileys/status'
import { Route as ApiBaileysSendMediaRouteImport } from './routes/api/baileys/send-media'
import { Route as ApiBaileysSendRouteImport } from './routes/api/baileys/send'
import { Route as ApiBaileysPresenceRouteImport } from './routes/api/baileys/presence'
import { Route as ApiBaileysMediaRouteImport } from './routes/api/baileys/media'
import { Route as ApiBaileysDisconnectRouteImport } from './routes/api/baileys/disconnect'
import { Route as ApiBaileysConnectRouteImport } from './routes/api/baileys/connect'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminResetRouteImport } from './routes/api/admin/reset'
import { Route as ApiSettingsRdCrmFieldsRouteImport } from './routes/api/settings/rd-crm/fields'
import { Route as ApiSettingsRdCrmCallbackRouteImport } from './routes/api/settings/rd-crm/callback'
import { Route as ApiContactsContactIdRdDealRouteImport } from './routes/api/contacts/$contactId/rd-deal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoomIdRoute = CallRoomIdRouteImport.update({
  id: '/call/$roomId',
  path: '/call/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSectorsRoute = ApiSectorsRouteImport.update({
  id: '/api/sectors',
  path: '/api/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickResponsesRoute = ApiQuickResponsesRouteImport.update({
  id: '/api/quick-responses',
  path: '/api/quick-responses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorsRoute = ApiOperatorsRouteImport.update({
  id: '/api/operators',
  path: '/api/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsRoute = ApiGroupsRouteImport.update({
  id: '/api/groups',
  path: '/api/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsRoute = ApiChatsRouteImport.update({
  id: '/api/chats',
  path: '/api/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallsRoute = ApiCallsRouteImport.update({
  id: '/api/calls',
  path: '/api/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValentinaSupervisorRoute = ApiValentinaSupervisorRouteImport.update({
  id: '/api/valentina/supervisor',
  path: '/api/valentina/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValentinaSdrRoute = ApiValentinaSdrRouteImport.update({
  id: '/api/valentina/sdr',
  path: '/api/valentina/sdr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValentinaRodizioRoute = ApiValentinaRodizioRouteImport.update({
  id: '/api/valentina/rodizio',
  path: '/api/valentina/rodizio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValentinaMessagesRoute = ApiValentinaMessagesRouteImport.update({
  id: '/api/valentina/messages',
  path: '/api/valentina/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValentinaKnowledgeRoute = ApiValentinaKnowledgeRouteImport.update({
  id: '/api/valentina/knowledge',
  path: '/api/valentina/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValentinaConfigRoute = ApiValentinaConfigRouteImport.update({
  id: '/api/valentina/config',
  path: '/api/valentina/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValentinaAgentsRoute = ApiValentinaAgentsRouteImport.update({
  id: '/api/valentina/agents',
  path: '/api/valentina/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsReportsRoute = ApiSettingsReportsRouteImport.update({
  id: '/api/settings/reports',
  path: '/api/settings/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRdCrmRoute = ApiSettingsRdCrmRouteImport.update({
  id: '/api/settings/rd-crm',
  path: '/api/settings/rd-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoTasksRoute = ApiGestaoTasksRouteImport.update({
  id: '/api/gestao/tasks',
  path: '/api/gestao/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoSlaRoute = ApiGestaoSlaRouteImport.update({
  id: '/api/gestao/sla',
  path: '/api/gestao/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoReportsRoute = ApiGestaoReportsRouteImport.update({
  id: '/api/gestao/reports',
  path: '/api/gestao/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoPerformanceRoute = ApiGestaoPerformanceRouteImport.update({
  id: '/api/gestao/performance',
  path: '/api/gestao/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoOverviewRoute = ApiGestaoOverviewRouteImport.update({
  id: '/api/gestao/overview',
  path: '/api/gestao/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoOperatorHistoryRoute =
  ApiGestaoOperatorHistoryRouteImport.update({
    id: '/api/gestao/operator-history',
    path: '/api/gestao/operator-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGestaoMyMetricsRoute = ApiGestaoMyMetricsRouteImport.update({
  id: '/api/gestao/my-metrics',
  path: '/api/gestao/my-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoMessagesRoute = ApiGestaoMessagesRouteImport.update({
  id: '/api/gestao/messages',
  path: '/api/gestao/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoLiveRoute = ApiGestaoLiveRouteImport.update({
  id: '/api/gestao/live',
  path: '/api/gestao/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoHealthRoute = ApiGestaoHealthRouteImport.update({
  id: '/api/gestao/health',
  path: '/api/gestao/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoCostsRoute = ApiGestaoCostsRouteImport.update({
  id: '/api/gestao/costs',
  path: '/api/gestao/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoContactsAnalyticsRoute =
  ApiGestaoContactsAnalyticsRouteImport.update({
    id: '/api/gestao/contacts-analytics',
    path: '/api/gestao/contacts-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGestaoAuditsRoute = ApiGestaoAuditsRouteImport.update({
  id: '/api/gestao/audits',
  path: '/api/gestao/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoAlertsRoute = ApiGestaoAlertsRouteImport.update({
  id: '/api/gestao/alerts',
  path: '/api/gestao/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsUpdateWalletRoute = ApiContactsUpdateWalletRouteImport.update({
  id: '/update-wallet',
  path: '/update-wallet',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiContactsContactIdRoute = ApiContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiChatsUpdateQueueRoute = ApiChatsUpdateQueueRouteImport.update({
  id: '/update-queue',
  path: '/update-queue',
  getParentRoute: () => ApiChatsRoute,
} as any)
const ApiBaileysSyncAvatarsRoute = ApiBaileysSyncAvatarsRouteImport.update({
  id: '/api/baileys/sync-avatars',
  path: '/api/baileys/sync-avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysStatusRoute = ApiBaileysStatusRouteImport.update({
  id: '/api/baileys/status',
  path: '/api/baileys/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysSendMediaRoute = ApiBaileysSendMediaRouteImport.update({
  id: '/api/baileys/send-media',
  path: '/api/baileys/send-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysSendRoute = ApiBaileysSendRouteImport.update({
  id: '/api/baileys/send',
  path: '/api/baileys/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysPresenceRoute = ApiBaileysPresenceRouteImport.update({
  id: '/api/baileys/presence',
  path: '/api/baileys/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysMediaRoute = ApiBaileysMediaRouteImport.update({
  id: '/api/baileys/media',
  path: '/api/baileys/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysDisconnectRoute = ApiBaileysDisconnectRouteImport.update({
  id: '/api/baileys/disconnect',
  path: '/api/baileys/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysConnectRoute = ApiBaileysConnectRouteImport.update({
  id: '/api/baileys/connect',
  path: '/api/baileys/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetRoute = ApiAdminResetRouteImport.update({
  id: '/api/admin/reset',
  path: '/api/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRdCrmFieldsRoute = ApiSettingsRdCrmFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => ApiSettingsRdCrmRoute,
} as any)
const ApiSettingsRdCrmCallbackRoute =
  ApiSettingsRdCrmCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiSettingsRdCrmRoute,
  } as any)
const ApiContactsContactIdRdDealRoute =
  ApiContactsContactIdRdDealRouteImport.update({
    id: '/rd-deal',
    path: '/rd-deal',
    getParentRoute: () => ApiContactsContactIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/groups': typeof ApiGroupsRoute
  '/api/operators': typeof ApiOperatorsRoute
  '/api/quick-responses': typeof ApiQuickResponsesRoute
  '/api/sectors': typeof ApiSectorsRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/api/admin/reset': typeof ApiAdminResetRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/presence': typeof ApiBaileysPresenceRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/send-media': typeof ApiBaileysSendMediaRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/baileys/sync-avatars': typeof ApiBaileysSyncAvatarsRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRouteWithChildren
  '/api/contacts/update-wallet': typeof ApiContactsUpdateWalletRoute
  '/api/gestao/alerts': typeof ApiGestaoAlertsRoute
  '/api/gestao/audits': typeof ApiGestaoAuditsRoute
  '/api/gestao/contacts-analytics': typeof ApiGestaoContactsAnalyticsRoute
  '/api/gestao/costs': typeof ApiGestaoCostsRoute
  '/api/gestao/health': typeof ApiGestaoHealthRoute
  '/api/gestao/live': typeof ApiGestaoLiveRoute
  '/api/gestao/messages': typeof ApiGestaoMessagesRoute
  '/api/gestao/my-metrics': typeof ApiGestaoMyMetricsRoute
  '/api/gestao/operator-history': typeof ApiGestaoOperatorHistoryRoute
  '/api/gestao/overview': typeof ApiGestaoOverviewRoute
  '/api/gestao/performance': typeof ApiGestaoPerformanceRoute
  '/api/gestao/reports': typeof ApiGestaoReportsRoute
  '/api/gestao/sla': typeof ApiGestaoSlaRoute
  '/api/gestao/tasks': typeof ApiGestaoTasksRoute
  '/api/settings/rd-crm': typeof ApiSettingsRdCrmRouteWithChildren
  '/api/settings/reports': typeof ApiSettingsReportsRoute
  '/api/valentina/agents': typeof ApiValentinaAgentsRoute
  '/api/valentina/config': typeof ApiValentinaConfigRoute
  '/api/valentina/knowledge': typeof ApiValentinaKnowledgeRoute
  '/api/valentina/messages': typeof ApiValentinaMessagesRoute
  '/api/valentina/rodizio': typeof ApiValentinaRodizioRoute
  '/api/valentina/sdr': typeof ApiValentinaSdrRoute
  '/api/valentina/supervisor': typeof ApiValentinaSupervisorRoute
  '/api/contacts/$contactId/rd-deal': typeof ApiContactsContactIdRdDealRoute
  '/api/settings/rd-crm/callback': typeof ApiSettingsRdCrmCallbackRoute
  '/api/settings/rd-crm/fields': typeof ApiSettingsRdCrmFieldsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/groups': typeof ApiGroupsRoute
  '/api/operators': typeof ApiOperatorsRoute
  '/api/quick-responses': typeof ApiQuickResponsesRoute
  '/api/sectors': typeof ApiSectorsRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/api/admin/reset': typeof ApiAdminResetRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/presence': typeof ApiBaileysPresenceRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/send-media': typeof ApiBaileysSendMediaRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/baileys/sync-avatars': typeof ApiBaileysSyncAvatarsRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRouteWithChildren
  '/api/contacts/update-wallet': typeof ApiContactsUpdateWalletRoute
  '/api/gestao/alerts': typeof ApiGestaoAlertsRoute
  '/api/gestao/audits': typeof ApiGestaoAuditsRoute
  '/api/gestao/contacts-analytics': typeof ApiGestaoContactsAnalyticsRoute
  '/api/gestao/costs': typeof ApiGestaoCostsRoute
  '/api/gestao/health': typeof ApiGestaoHealthRoute
  '/api/gestao/live': typeof ApiGestaoLiveRoute
  '/api/gestao/messages': typeof ApiGestaoMessagesRoute
  '/api/gestao/my-metrics': typeof ApiGestaoMyMetricsRoute
  '/api/gestao/operator-history': typeof ApiGestaoOperatorHistoryRoute
  '/api/gestao/overview': typeof ApiGestaoOverviewRoute
  '/api/gestao/performance': typeof ApiGestaoPerformanceRoute
  '/api/gestao/reports': typeof ApiGestaoReportsRoute
  '/api/gestao/sla': typeof ApiGestaoSlaRoute
  '/api/gestao/tasks': typeof ApiGestaoTasksRoute
  '/api/settings/rd-crm': typeof ApiSettingsRdCrmRouteWithChildren
  '/api/settings/reports': typeof ApiSettingsReportsRoute
  '/api/valentina/agents': typeof ApiValentinaAgentsRoute
  '/api/valentina/config': typeof ApiValentinaConfigRoute
  '/api/valentina/knowledge': typeof ApiValentinaKnowledgeRoute
  '/api/valentina/messages': typeof ApiValentinaMessagesRoute
  '/api/valentina/rodizio': typeof ApiValentinaRodizioRoute
  '/api/valentina/sdr': typeof ApiValentinaSdrRoute
  '/api/valentina/supervisor': typeof ApiValentinaSupervisorRoute
  '/api/contacts/$contactId/rd-deal': typeof ApiContactsContactIdRdDealRoute
  '/api/settings/rd-crm/callback': typeof ApiSettingsRdCrmCallbackRoute
  '/api/settings/rd-crm/fields': typeof ApiSettingsRdCrmFieldsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/calls': typeof ApiCallsRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/groups': typeof ApiGroupsRoute
  '/api/operators': typeof ApiOperatorsRoute
  '/api/quick-responses': typeof ApiQuickResponsesRoute
  '/api/sectors': typeof ApiSectorsRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/call/$roomId': typeof CallRoomIdRoute
  '/api/admin/reset': typeof ApiAdminResetRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/presence': typeof ApiBaileysPresenceRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/send-media': typeof ApiBaileysSendMediaRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/baileys/sync-avatars': typeof ApiBaileysSyncAvatarsRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
  '/api/contacts/$contactId': typeof ApiContactsContactIdRouteWithChildren
  '/api/contacts/update-wallet': typeof ApiContactsUpdateWalletRoute
  '/api/gestao/alerts': typeof ApiGestaoAlertsRoute
  '/api/gestao/audits': typeof ApiGestaoAuditsRoute
  '/api/gestao/contacts-analytics': typeof ApiGestaoContactsAnalyticsRoute
  '/api/gestao/costs': typeof ApiGestaoCostsRoute
  '/api/gestao/health': typeof ApiGestaoHealthRoute
  '/api/gestao/live': typeof ApiGestaoLiveRoute
  '/api/gestao/messages': typeof ApiGestaoMessagesRoute
  '/api/gestao/my-metrics': typeof ApiGestaoMyMetricsRoute
  '/api/gestao/operator-history': typeof ApiGestaoOperatorHistoryRoute
  '/api/gestao/overview': typeof ApiGestaoOverviewRoute
  '/api/gestao/performance': typeof ApiGestaoPerformanceRoute
  '/api/gestao/reports': typeof ApiGestaoReportsRoute
  '/api/gestao/sla': typeof ApiGestaoSlaRoute
  '/api/gestao/tasks': typeof ApiGestaoTasksRoute
  '/api/settings/rd-crm': typeof ApiSettingsRdCrmRouteWithChildren
  '/api/settings/reports': typeof ApiSettingsReportsRoute
  '/api/valentina/agents': typeof ApiValentinaAgentsRoute
  '/api/valentina/config': typeof ApiValentinaConfigRoute
  '/api/valentina/knowledge': typeof ApiValentinaKnowledgeRoute
  '/api/valentina/messages': typeof ApiValentinaMessagesRoute
  '/api/valentina/rodizio': typeof ApiValentinaRodizioRoute
  '/api/valentina/sdr': typeof ApiValentinaSdrRoute
  '/api/valentina/supervisor': typeof ApiValentinaSupervisorRoute
  '/api/contacts/$contactId/rd-deal': typeof ApiContactsContactIdRdDealRoute
  '/api/settings/rd-crm/callback': typeof ApiSettingsRdCrmCallbackRoute
  '/api/settings/rd-crm/fields': typeof ApiSettingsRdCrmFieldsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/calls'
    | '/api/chats'
    | '/api/contacts'
    | '/api/groups'
    | '/api/operators'
    | '/api/quick-responses'
    | '/api/sectors'
    | '/api/tasks'
    | '/api/templates'
    | '/call/$roomId'
    | '/api/admin/reset'
    | '/api/auth/login'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/presence'
    | '/api/baileys/send'
    | '/api/baileys/send-media'
    | '/api/baileys/status'
    | '/api/baileys/sync-avatars'
    | '/api/chats/update-queue'
    | '/api/contacts/$contactId'
    | '/api/contacts/update-wallet'
    | '/api/gestao/alerts'
    | '/api/gestao/audits'
    | '/api/gestao/contacts-analytics'
    | '/api/gestao/costs'
    | '/api/gestao/health'
    | '/api/gestao/live'
    | '/api/gestao/messages'
    | '/api/gestao/my-metrics'
    | '/api/gestao/operator-history'
    | '/api/gestao/overview'
    | '/api/gestao/performance'
    | '/api/gestao/reports'
    | '/api/gestao/sla'
    | '/api/gestao/tasks'
    | '/api/settings/rd-crm'
    | '/api/settings/reports'
    | '/api/valentina/agents'
    | '/api/valentina/config'
    | '/api/valentina/knowledge'
    | '/api/valentina/messages'
    | '/api/valentina/rodizio'
    | '/api/valentina/sdr'
    | '/api/valentina/supervisor'
    | '/api/contacts/$contactId/rd-deal'
    | '/api/settings/rd-crm/callback'
    | '/api/settings/rd-crm/fields'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/calls'
    | '/api/chats'
    | '/api/contacts'
    | '/api/groups'
    | '/api/operators'
    | '/api/quick-responses'
    | '/api/sectors'
    | '/api/tasks'
    | '/api/templates'
    | '/call/$roomId'
    | '/api/admin/reset'
    | '/api/auth/login'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/presence'
    | '/api/baileys/send'
    | '/api/baileys/send-media'
    | '/api/baileys/status'
    | '/api/baileys/sync-avatars'
    | '/api/chats/update-queue'
    | '/api/contacts/$contactId'
    | '/api/contacts/update-wallet'
    | '/api/gestao/alerts'
    | '/api/gestao/audits'
    | '/api/gestao/contacts-analytics'
    | '/api/gestao/costs'
    | '/api/gestao/health'
    | '/api/gestao/live'
    | '/api/gestao/messages'
    | '/api/gestao/my-metrics'
    | '/api/gestao/operator-history'
    | '/api/gestao/overview'
    | '/api/gestao/performance'
    | '/api/gestao/reports'
    | '/api/gestao/sla'
    | '/api/gestao/tasks'
    | '/api/settings/rd-crm'
    | '/api/settings/reports'
    | '/api/valentina/agents'
    | '/api/valentina/config'
    | '/api/valentina/knowledge'
    | '/api/valentina/messages'
    | '/api/valentina/rodizio'
    | '/api/valentina/sdr'
    | '/api/valentina/supervisor'
    | '/api/contacts/$contactId/rd-deal'
    | '/api/settings/rd-crm/callback'
    | '/api/settings/rd-crm/fields'
  id:
    | '__root__'
    | '/'
    | '/api/calls'
    | '/api/chats'
    | '/api/contacts'
    | '/api/groups'
    | '/api/operators'
    | '/api/quick-responses'
    | '/api/sectors'
    | '/api/tasks'
    | '/api/templates'
    | '/call/$roomId'
    | '/api/admin/reset'
    | '/api/auth/login'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/presence'
    | '/api/baileys/send'
    | '/api/baileys/send-media'
    | '/api/baileys/status'
    | '/api/baileys/sync-avatars'
    | '/api/chats/update-queue'
    | '/api/contacts/$contactId'
    | '/api/contacts/update-wallet'
    | '/api/gestao/alerts'
    | '/api/gestao/audits'
    | '/api/gestao/contacts-analytics'
    | '/api/gestao/costs'
    | '/api/gestao/health'
    | '/api/gestao/live'
    | '/api/gestao/messages'
    | '/api/gestao/my-metrics'
    | '/api/gestao/operator-history'
    | '/api/gestao/overview'
    | '/api/gestao/performance'
    | '/api/gestao/reports'
    | '/api/gestao/sla'
    | '/api/gestao/tasks'
    | '/api/settings/rd-crm'
    | '/api/settings/reports'
    | '/api/valentina/agents'
    | '/api/valentina/config'
    | '/api/valentina/knowledge'
    | '/api/valentina/messages'
    | '/api/valentina/rodizio'
    | '/api/valentina/sdr'
    | '/api/valentina/supervisor'
    | '/api/contacts/$contactId/rd-deal'
    | '/api/settings/rd-crm/callback'
    | '/api/settings/rd-crm/fields'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCallsRoute: typeof ApiCallsRoute
  ApiChatsRoute: typeof ApiChatsRouteWithChildren
  ApiContactsRoute: typeof ApiContactsRouteWithChildren
  ApiGroupsRoute: typeof ApiGroupsRoute
  ApiOperatorsRoute: typeof ApiOperatorsRoute
  ApiQuickResponsesRoute: typeof ApiQuickResponsesRoute
  ApiSectorsRoute: typeof ApiSectorsRoute
  ApiTasksRoute: typeof ApiTasksRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  CallRoomIdRoute: typeof CallRoomIdRoute
  ApiAdminResetRoute: typeof ApiAdminResetRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiBaileysConnectRoute: typeof ApiBaileysConnectRoute
  ApiBaileysDisconnectRoute: typeof ApiBaileysDisconnectRoute
  ApiBaileysMediaRoute: typeof ApiBaileysMediaRoute
  ApiBaileysPresenceRoute: typeof ApiBaileysPresenceRoute
  ApiBaileysSendRoute: typeof ApiBaileysSendRoute
  ApiBaileysSendMediaRoute: typeof ApiBaileysSendMediaRoute
  ApiBaileysStatusRoute: typeof ApiBaileysStatusRoute
  ApiBaileysSyncAvatarsRoute: typeof ApiBaileysSyncAvatarsRoute
  ApiGestaoAlertsRoute: typeof ApiGestaoAlertsRoute
  ApiGestaoAuditsRoute: typeof ApiGestaoAuditsRoute
  ApiGestaoContactsAnalyticsRoute: typeof ApiGestaoContactsAnalyticsRoute
  ApiGestaoCostsRoute: typeof ApiGestaoCostsRoute
  ApiGestaoHealthRoute: typeof ApiGestaoHealthRoute
  ApiGestaoLiveRoute: typeof ApiGestaoLiveRoute
  ApiGestaoMessagesRoute: typeof ApiGestaoMessagesRoute
  ApiGestaoMyMetricsRoute: typeof ApiGestaoMyMetricsRoute
  ApiGestaoOperatorHistoryRoute: typeof ApiGestaoOperatorHistoryRoute
  ApiGestaoOverviewRoute: typeof ApiGestaoOverviewRoute
  ApiGestaoPerformanceRoute: typeof ApiGestaoPerformanceRoute
  ApiGestaoReportsRoute: typeof ApiGestaoReportsRoute
  ApiGestaoSlaRoute: typeof ApiGestaoSlaRoute
  ApiGestaoTasksRoute: typeof ApiGestaoTasksRoute
  ApiSettingsRdCrmRoute: typeof ApiSettingsRdCrmRouteWithChildren
  ApiSettingsReportsRoute: typeof ApiSettingsReportsRoute
  ApiValentinaAgentsRoute: typeof ApiValentinaAgentsRoute
  ApiValentinaConfigRoute: typeof ApiValentinaConfigRoute
  ApiValentinaKnowledgeRoute: typeof ApiValentinaKnowledgeRoute
  ApiValentinaMessagesRoute: typeof ApiValentinaMessagesRoute
  ApiValentinaRodizioRoute: typeof ApiValentinaRodizioRoute
  ApiValentinaSdrRoute: typeof ApiValentinaSdrRoute
  ApiValentinaSupervisorRoute: typeof ApiValentinaSupervisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$roomId': {
      id: '/call/$roomId'
      path: '/call/$roomId'
      fullPath: '/call/$roomId'
      preLoaderRoute: typeof CallRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sectors': {
      id: '/api/sectors'
      path: '/api/sectors'
      fullPath: '/api/sectors'
      preLoaderRoute: typeof ApiSectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-responses': {
      id: '/api/quick-responses'
      path: '/api/quick-responses'
      fullPath: '/api/quick-responses'
      preLoaderRoute: typeof ApiQuickResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operators': {
      id: '/api/operators'
      path: '/api/operators'
      fullPath: '/api/operators'
      preLoaderRoute: typeof ApiOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups': {
      id: '/api/groups'
      path: '/api/groups'
      fullPath: '/api/groups'
      preLoaderRoute: typeof ApiGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats': {
      id: '/api/chats'
      path: '/api/chats'
      fullPath: '/api/chats'
      preLoaderRoute: typeof ApiChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calls': {
      id: '/api/calls'
      path: '/api/calls'
      fullPath: '/api/calls'
      preLoaderRoute: typeof ApiCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/valentina/supervisor': {
      id: '/api/valentina/supervisor'
      path: '/api/valentina/supervisor'
      fullPath: '/api/valentina/supervisor'
      preLoaderRoute: typeof ApiValentinaSupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/valentina/sdr': {
      id: '/api/valentina/sdr'
      path: '/api/valentina/sdr'
      fullPath: '/api/valentina/sdr'
      preLoaderRoute: typeof ApiValentinaSdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/valentina/rodizio': {
      id: '/api/valentina/rodizio'
      path: '/api/valentina/rodizio'
      fullPath: '/api/valentina/rodizio'
      preLoaderRoute: typeof ApiValentinaRodizioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/valentina/messages': {
      id: '/api/valentina/messages'
      path: '/api/valentina/messages'
      fullPath: '/api/valentina/messages'
      preLoaderRoute: typeof ApiValentinaMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/valentina/knowledge': {
      id: '/api/valentina/knowledge'
      path: '/api/valentina/knowledge'
      fullPath: '/api/valentina/knowledge'
      preLoaderRoute: typeof ApiValentinaKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/valentina/config': {
      id: '/api/valentina/config'
      path: '/api/valentina/config'
      fullPath: '/api/valentina/config'
      preLoaderRoute: typeof ApiValentinaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/valentina/agents': {
      id: '/api/valentina/agents'
      path: '/api/valentina/agents'
      fullPath: '/api/valentina/agents'
      preLoaderRoute: typeof ApiValentinaAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/reports': {
      id: '/api/settings/reports'
      path: '/api/settings/reports'
      fullPath: '/api/settings/reports'
      preLoaderRoute: typeof ApiSettingsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/rd-crm': {
      id: '/api/settings/rd-crm'
      path: '/api/settings/rd-crm'
      fullPath: '/api/settings/rd-crm'
      preLoaderRoute: typeof ApiSettingsRdCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/tasks': {
      id: '/api/gestao/tasks'
      path: '/api/gestao/tasks'
      fullPath: '/api/gestao/tasks'
      preLoaderRoute: typeof ApiGestaoTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/sla': {
      id: '/api/gestao/sla'
      path: '/api/gestao/sla'
      fullPath: '/api/gestao/sla'
      preLoaderRoute: typeof ApiGestaoSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/reports': {
      id: '/api/gestao/reports'
      path: '/api/gestao/reports'
      fullPath: '/api/gestao/reports'
      preLoaderRoute: typeof ApiGestaoReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/performance': {
      id: '/api/gestao/performance'
      path: '/api/gestao/performance'
      fullPath: '/api/gestao/performance'
      preLoaderRoute: typeof ApiGestaoPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/overview': {
      id: '/api/gestao/overview'
      path: '/api/gestao/overview'
      fullPath: '/api/gestao/overview'
      preLoaderRoute: typeof ApiGestaoOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/operator-history': {
      id: '/api/gestao/operator-history'
      path: '/api/gestao/operator-history'
      fullPath: '/api/gestao/operator-history'
      preLoaderRoute: typeof ApiGestaoOperatorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/my-metrics': {
      id: '/api/gestao/my-metrics'
      path: '/api/gestao/my-metrics'
      fullPath: '/api/gestao/my-metrics'
      preLoaderRoute: typeof ApiGestaoMyMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/messages': {
      id: '/api/gestao/messages'
      path: '/api/gestao/messages'
      fullPath: '/api/gestao/messages'
      preLoaderRoute: typeof ApiGestaoMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/live': {
      id: '/api/gestao/live'
      path: '/api/gestao/live'
      fullPath: '/api/gestao/live'
      preLoaderRoute: typeof ApiGestaoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/health': {
      id: '/api/gestao/health'
      path: '/api/gestao/health'
      fullPath: '/api/gestao/health'
      preLoaderRoute: typeof ApiGestaoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/costs': {
      id: '/api/gestao/costs'
      path: '/api/gestao/costs'
      fullPath: '/api/gestao/costs'
      preLoaderRoute: typeof ApiGestaoCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/contacts-analytics': {
      id: '/api/gestao/contacts-analytics'
      path: '/api/gestao/contacts-analytics'
      fullPath: '/api/gestao/contacts-analytics'
      preLoaderRoute: typeof ApiGestaoContactsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/audits': {
      id: '/api/gestao/audits'
      path: '/api/gestao/audits'
      fullPath: '/api/gestao/audits'
      preLoaderRoute: typeof ApiGestaoAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/alerts': {
      id: '/api/gestao/alerts'
      path: '/api/gestao/alerts'
      fullPath: '/api/gestao/alerts'
      preLoaderRoute: typeof ApiGestaoAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts/update-wallet': {
      id: '/api/contacts/update-wallet'
      path: '/update-wallet'
      fullPath: '/api/contacts/update-wallet'
      preLoaderRoute: typeof ApiContactsUpdateWalletRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/contacts/$contactId': {
      id: '/api/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/api/contacts/$contactId'
      preLoaderRoute: typeof ApiContactsContactIdRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/chats/update-queue': {
      id: '/api/chats/update-queue'
      path: '/update-queue'
      fullPath: '/api/chats/update-queue'
      preLoaderRoute: typeof ApiChatsUpdateQueueRouteImport
      parentRoute: typeof ApiChatsRoute
    }
    '/api/baileys/sync-avatars': {
      id: '/api/baileys/sync-avatars'
      path: '/api/baileys/sync-avatars'
      fullPath: '/api/baileys/sync-avatars'
      preLoaderRoute: typeof ApiBaileysSyncAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/status': {
      id: '/api/baileys/status'
      path: '/api/baileys/status'
      fullPath: '/api/baileys/status'
      preLoaderRoute: typeof ApiBaileysStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/send-media': {
      id: '/api/baileys/send-media'
      path: '/api/baileys/send-media'
      fullPath: '/api/baileys/send-media'
      preLoaderRoute: typeof ApiBaileysSendMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/send': {
      id: '/api/baileys/send'
      path: '/api/baileys/send'
      fullPath: '/api/baileys/send'
      preLoaderRoute: typeof ApiBaileysSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/presence': {
      id: '/api/baileys/presence'
      path: '/api/baileys/presence'
      fullPath: '/api/baileys/presence'
      preLoaderRoute: typeof ApiBaileysPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/media': {
      id: '/api/baileys/media'
      path: '/api/baileys/media'
      fullPath: '/api/baileys/media'
      preLoaderRoute: typeof ApiBaileysMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/disconnect': {
      id: '/api/baileys/disconnect'
      path: '/api/baileys/disconnect'
      fullPath: '/api/baileys/disconnect'
      preLoaderRoute: typeof ApiBaileysDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/connect': {
      id: '/api/baileys/connect'
      path: '/api/baileys/connect'
      fullPath: '/api/baileys/connect'
      preLoaderRoute: typeof ApiBaileysConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reset': {
      id: '/api/admin/reset'
      path: '/api/admin/reset'
      fullPath: '/api/admin/reset'
      preLoaderRoute: typeof ApiAdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/rd-crm/fields': {
      id: '/api/settings/rd-crm/fields'
      path: '/fields'
      fullPath: '/api/settings/rd-crm/fields'
      preLoaderRoute: typeof ApiSettingsRdCrmFieldsRouteImport
      parentRoute: typeof ApiSettingsRdCrmRoute
    }
    '/api/settings/rd-crm/callback': {
      id: '/api/settings/rd-crm/callback'
      path: '/callback'
      fullPath: '/api/settings/rd-crm/callback'
      preLoaderRoute: typeof ApiSettingsRdCrmCallbackRouteImport
      parentRoute: typeof ApiSettingsRdCrmRoute
    }
    '/api/contacts/$contactId/rd-deal': {
      id: '/api/contacts/$contactId/rd-deal'
      path: '/rd-deal'
      fullPath: '/api/contacts/$contactId/rd-deal'
      preLoaderRoute: typeof ApiContactsContactIdRdDealRouteImport
      parentRoute: typeof ApiContactsContactIdRoute
    }
  }
}

interface ApiChatsRouteChildren {
  ApiChatsUpdateQueueRoute: typeof ApiChatsUpdateQueueRoute
}

const ApiChatsRouteChildren: ApiChatsRouteChildren = {
  ApiChatsUpdateQueueRoute: ApiChatsUpdateQueueRoute,
}

const ApiChatsRouteWithChildren = ApiChatsRoute._addFileChildren(
  ApiChatsRouteChildren,
)

interface ApiContactsContactIdRouteChildren {
  ApiContactsContactIdRdDealRoute: typeof ApiContactsContactIdRdDealRoute
}

const ApiContactsContactIdRouteChildren: ApiContactsContactIdRouteChildren = {
  ApiContactsContactIdRdDealRoute: ApiContactsContactIdRdDealRoute,
}

const ApiContactsContactIdRouteWithChildren =
  ApiContactsContactIdRoute._addFileChildren(ApiContactsContactIdRouteChildren)

interface ApiContactsRouteChildren {
  ApiContactsContactIdRoute: typeof ApiContactsContactIdRouteWithChildren
  ApiContactsUpdateWalletRoute: typeof ApiContactsUpdateWalletRoute
}

const ApiContactsRouteChildren: ApiContactsRouteChildren = {
  ApiContactsContactIdRoute: ApiContactsContactIdRouteWithChildren,
  ApiContactsUpdateWalletRoute: ApiContactsUpdateWalletRoute,
}

const ApiContactsRouteWithChildren = ApiContactsRoute._addFileChildren(
  ApiContactsRouteChildren,
)

interface ApiSettingsRdCrmRouteChildren {
  ApiSettingsRdCrmCallbackRoute: typeof ApiSettingsRdCrmCallbackRoute
  ApiSettingsRdCrmFieldsRoute: typeof ApiSettingsRdCrmFieldsRoute
}

const ApiSettingsRdCrmRouteChildren: ApiSettingsRdCrmRouteChildren = {
  ApiSettingsRdCrmCallbackRoute: ApiSettingsRdCrmCallbackRoute,
  ApiSettingsRdCrmFieldsRoute: ApiSettingsRdCrmFieldsRoute,
}

const ApiSettingsRdCrmRouteWithChildren =
  ApiSettingsRdCrmRoute._addFileChildren(ApiSettingsRdCrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCallsRoute: ApiCallsRoute,
  ApiChatsRoute: ApiChatsRouteWithChildren,
  ApiContactsRoute: ApiContactsRouteWithChildren,
  ApiGroupsRoute: ApiGroupsRoute,
  ApiOperatorsRoute: ApiOperatorsRoute,
  ApiQuickResponsesRoute: ApiQuickResponsesRoute,
  ApiSectorsRoute: ApiSectorsRoute,
  ApiTasksRoute: ApiTasksRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  CallRoomIdRoute: CallRoomIdRoute,
  ApiAdminResetRoute: ApiAdminResetRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiBaileysConnectRoute: ApiBaileysConnectRoute,
  ApiBaileysDisconnectRoute: ApiBaileysDisconnectRoute,
  ApiBaileysMediaRoute: ApiBaileysMediaRoute,
  ApiBaileysPresenceRoute: ApiBaileysPresenceRoute,
  ApiBaileysSendRoute: ApiBaileysSendRoute,
  ApiBaileysSendMediaRoute: ApiBaileysSendMediaRoute,
  ApiBaileysStatusRoute: ApiBaileysStatusRoute,
  ApiBaileysSyncAvatarsRoute: ApiBaileysSyncAvatarsRoute,
  ApiGestaoAlertsRoute: ApiGestaoAlertsRoute,
  ApiGestaoAuditsRoute: ApiGestaoAuditsRoute,
  ApiGestaoContactsAnalyticsRoute: ApiGestaoContactsAnalyticsRoute,
  ApiGestaoCostsRoute: ApiGestaoCostsRoute,
  ApiGestaoHealthRoute: ApiGestaoHealthRoute,
  ApiGestaoLiveRoute: ApiGestaoLiveRoute,
  ApiGestaoMessagesRoute: ApiGestaoMessagesRoute,
  ApiGestaoMyMetricsRoute: ApiGestaoMyMetricsRoute,
  ApiGestaoOperatorHistoryRoute: ApiGestaoOperatorHistoryRoute,
  ApiGestaoOverviewRoute: ApiGestaoOverviewRoute,
  ApiGestaoPerformanceRoute: ApiGestaoPerformanceRoute,
  ApiGestaoReportsRoute: ApiGestaoReportsRoute,
  ApiGestaoSlaRoute: ApiGestaoSlaRoute,
  ApiGestaoTasksRoute: ApiGestaoTasksRoute,
  ApiSettingsRdCrmRoute: ApiSettingsRdCrmRouteWithChildren,
  ApiSettingsReportsRoute: ApiSettingsReportsRoute,
  ApiValentinaAgentsRoute: ApiValentinaAgentsRoute,
  ApiValentinaConfigRoute: ApiValentinaConfigRoute,
  ApiValentinaKnowledgeRoute: ApiValentinaKnowledgeRoute,
  ApiValentinaMessagesRoute: ApiValentinaMessagesRoute,
  ApiValentinaRodizioRoute: ApiValentinaRodizioRoute,
  ApiValentinaSdrRoute: ApiValentinaSdrRoute,
  ApiValentinaSupervisorRoute: ApiValentinaSupervisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
