/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOperatorsRouteImport } from './routes/api/operators'
import { Route as ApiChatsRouteImport } from './routes/api/chats'
import { Route as ApiChatsUpdateQueueRouteImport } from './routes/api/chats/update-queue'
import { Route as ApiBaileysStatusRouteImport } from './routes/api/baileys/status'
import { Route as ApiBaileysSendRouteImport } from './routes/api/baileys/send'
import { Route as ApiBaileysMediaRouteImport } from './routes/api/baileys/media'
import { Route as ApiBaileysDisconnectRouteImport } from './routes/api/baileys/disconnect'
import { Route as ApiBaileysConnectRouteImport } from './routes/api/baileys/connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperatorsRoute = ApiOperatorsRouteImport.update({
  id: '/api/operators',
  path: '/api/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsRoute = ApiChatsRouteImport.update({
  id: '/api/chats',
  path: '/api/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsUpdateQueueRoute = ApiChatsUpdateQueueRouteImport.update({
  id: '/update-queue',
  path: '/update-queue',
  getParentRoute: () => ApiChatsRoute,
} as any)
const ApiBaileysStatusRoute = ApiBaileysStatusRouteImport.update({
  id: '/api/baileys/status',
  path: '/api/baileys/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysSendRoute = ApiBaileysSendRouteImport.update({
  id: '/api/baileys/send',
  path: '/api/baileys/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysMediaRoute = ApiBaileysMediaRouteImport.update({
  id: '/api/baileys/media',
  path: '/api/baileys/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysDisconnectRoute = ApiBaileysDisconnectRouteImport.update({
  id: '/api/baileys/disconnect',
  path: '/api/baileys/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaileysConnectRoute = ApiBaileysConnectRouteImport.update({
  id: '/api/baileys/connect',
  path: '/api/baileys/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/operators': typeof ApiOperatorsRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/operators': typeof ApiOperatorsRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chats': typeof ApiChatsRouteWithChildren
  '/api/operators': typeof ApiOperatorsRoute
  '/api/baileys/connect': typeof ApiBaileysConnectRoute
  '/api/baileys/disconnect': typeof ApiBaileysDisconnectRoute
  '/api/baileys/media': typeof ApiBaileysMediaRoute
  '/api/baileys/send': typeof ApiBaileysSendRoute
  '/api/baileys/status': typeof ApiBaileysStatusRoute
  '/api/chats/update-queue': typeof ApiChatsUpdateQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chats'
    | '/api/operators'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/send'
    | '/api/baileys/status'
    | '/api/chats/update-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chats'
    | '/api/operators'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/send'
    | '/api/baileys/status'
    | '/api/chats/update-queue'
  id:
    | '__root__'
    | '/'
    | '/api/chats'
    | '/api/operators'
    | '/api/baileys/connect'
    | '/api/baileys/disconnect'
    | '/api/baileys/media'
    | '/api/baileys/send'
    | '/api/baileys/status'
    | '/api/chats/update-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatsRoute: typeof ApiChatsRouteWithChildren
  ApiOperatorsRoute: typeof ApiOperatorsRoute
  ApiBaileysConnectRoute: typeof ApiBaileysConnectRoute
  ApiBaileysDisconnectRoute: typeof ApiBaileysDisconnectRoute
  ApiBaileysMediaRoute: typeof ApiBaileysMediaRoute
  ApiBaileysSendRoute: typeof ApiBaileysSendRoute
  ApiBaileysStatusRoute: typeof ApiBaileysStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operators': {
      id: '/api/operators'
      path: '/api/operators'
      fullPath: '/api/operators'
      preLoaderRoute: typeof ApiOperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats': {
      id: '/api/chats'
      path: '/api/chats'
      fullPath: '/api/chats'
      preLoaderRoute: typeof ApiChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/update-queue': {
      id: '/api/chats/update-queue'
      path: '/update-queue'
      fullPath: '/api/chats/update-queue'
      preLoaderRoute: typeof ApiChatsUpdateQueueRouteImport
      parentRoute: typeof ApiChatsRoute
    }
    '/api/baileys/status': {
      id: '/api/baileys/status'
      path: '/api/baileys/status'
      fullPath: '/api/baileys/status'
      preLoaderRoute: typeof ApiBaileysStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/send': {
      id: '/api/baileys/send'
      path: '/api/baileys/send'
      fullPath: '/api/baileys/send'
      preLoaderRoute: typeof ApiBaileysSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/media': {
      id: '/api/baileys/media'
      path: '/api/baileys/media'
      fullPath: '/api/baileys/media'
      preLoaderRoute: typeof ApiBaileysMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/disconnect': {
      id: '/api/baileys/disconnect'
      path: '/api/baileys/disconnect'
      fullPath: '/api/baileys/disconnect'
      preLoaderRoute: typeof ApiBaileysDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baileys/connect': {
      id: '/api/baileys/connect'
      path: '/api/baileys/connect'
      fullPath: '/api/baileys/connect'
      preLoaderRoute: typeof ApiBaileysConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiChatsRouteChildren {
  ApiChatsUpdateQueueRoute: typeof ApiChatsUpdateQueueRoute
}

const ApiChatsRouteChildren: ApiChatsRouteChildren = {
  ApiChatsUpdateQueueRoute: ApiChatsUpdateQueueRoute,
}

const ApiChatsRouteWithChildren = ApiChatsRoute._addFileChildren(
  ApiChatsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatsRoute: ApiChatsRouteWithChildren,
  ApiOperatorsRoute: ApiOperatorsRoute,
  ApiBaileysConnectRoute: ApiBaileysConnectRoute,
  ApiBaileysDisconnectRoute: ApiBaileysDisconnectRoute,
  ApiBaileysMediaRoute: ApiBaileysMediaRoute,
  ApiBaileysSendRoute: ApiBaileysSendRoute,
  ApiBaileysStatusRoute: ApiBaileysStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
